### PR TITLE
LPS-53022 - Add unit tests to check the extraction of the values of each field to be indexed.

### PR DESCRIPTION
**Pull request by natocesarrego**
Hi @arboliveira,

This is the pull which I've mentioned to you in https://github.com/arboliveira/liferay-portal/pull/312#issuecomment-324151961. Additionally, the https://github.com/arboliveira/liferay-portal/pull/312 is necessary to allow the unit test **testIndexDateFieldWithUSLocale** pass. This is a new test created by me in this pull.

If you need any other clarification, please let me know.

Thanks.

@marcellustavares

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hey @arboliveira,

Any update on this?

Thanks.

**Comment by arboliveira** [comment]
Exactly what I needed, with this I was able to derive the minimal unit test I wanted to replicate the NPE. Thanks!!

https://github.com/brianchandotcom/liferay-portal/pull/51764/commits/8938398b3b2e1c40462802a52dfa6b36780533c3

**Comment by arboliveira** [comment]
I think we should maybe try to make `DDMIndexerImpl` work without having to modify `DDMIndexerImplTest` like this?

https://github.com/arboliveira/com-liferay-dynamic-data-mapping/pull/2/commits/7b8140b9714dbaaaae3800374687af7ea78d086b 

I noticed that `DDMFormValues` does support adding several `DDMFormValue` instances for the same field name. There's even a test in place to validate this use case:

https://github.com/liferay/com-liferay-dynamic-data-mapping/blob/4544e3e15af6060c86ad80f5842f969fa8a7006f/dynamic-data-mapping-test/src/test/java/com/liferay/dynamic/data/mapping/storage/DDMFormValuesTest.java#L33-L54

I see that the change to `DDMIndexerImplTest` - to invoke `createDDMFormFieldValue` only once per field - was made because the new logic in `DDMIndexerImpl` will index Japanese content into the English field  (causing the test to break) if `createDDMFormFieldValue` is invoked several times. But if we don't cover this use case, and applications out there do invoke it several times per field, this "language shuffle" could make its way into production… 😬 

Certainly `DDMIndexerImpl` could be reinforced to account for this variation of `DDMFormValues` like before?  :grin:

**Comment by natocesarrego** [comment]
Hi @arboliveira,

I see your point. Just to make sure we're a both on the same page, your concern is about a wrong call to the **DDMFormValues** API by a customized development? Because the current logic of a single **DDMFormFieldValue** have one value for each language is the correct use of the API.

Best.

**Comment by arboliveira** [comment]
Customized development, certainly; but it could happen even in regular continued Forms development - if someone eventually writes more multi language features, and ends up invoking this API in the same way `DDMIndexerImplTest` did. If you tell me the correct use of the API is to concentrate all translations for the same field in a single `DDMFormFieldValue`, then I do agree that `DDMIndexerImplTest` should indeed be changed to reflect correct use. However, shouldn't then `DDMFormValues` throw an exception on incorrect usage, when attempting to add more than one `DDMFormFieldValue` for the same field with different translations? And this restriction could be enforced and documented in `DDMFormValuesTest` as a new test case. While it isn't so, though, if the API allows `DDMFormValues` to enter inconsistent state then `DDMIndexerImpl` should be prepared - to either reject the inconsistent state (with an exception of its own) or to tolerate it and index any Japanese content into Japanese fields.

**Comment by natocesarrego** [comment]
Nice catch and explanation, @arboliveira. 😉 I agree with you that it should be clearer in the code and in the documentation. I'll talk to Marcellus about this scenario raised by you.

Thanks for your feedback.

**Pull request closed without merging**
